version: "3"

services:

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=todo-list
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"